#!/bin/bash
#SBATCH -p m4
#SBATCH -n 1
#SBATCH --cpus-per-task=4
#SBATCH --qos=yushan
#SBATCH --account=yushan
#SBATCH --ntasks-per-core=1
#SBATCH -J equil
#SBATCH -o runout.%j
#SBATCH -e runerr.%j
#SBATCH -t 7-00:00:00
#SBATCH --time=7-00:00:00
#SBATCH --export=ALL
 
TOP=TEMP

gmx_mpi grompp -f equil_npt.mdp -c ../equil_nvt/prod.gro -p ../$TOP -o start.tpr &> grompp.log 
mpiexec -np 1 gmx_mpi mdrun -v -ntomp 4 -s start.tpr -deffnm prod 
